export const DETAILS: Record<string, string> = {
  aip: 'O Índice Aterogênico do Plasma (AIP) é a razão logarítmica entre triglicerídeos e colesterol HDL, servindo como marcador substituto para partículas LDL pequenas e densas — o subtipo mais aterogênico. Correlaciona-se com o tamanho das partículas LDL, cuja medição direta é cara e pouco acessível. Validado em múltiplas populações, incluindo coortes latino-americanas. O AIP é particularmente útil no contexto de síndrome metabólica e diabetes, pois captura risco cardiovascular que o LDL-C isolado pode não detectar.',

  apri: 'O APRI (AST to Platelet Ratio Index) é um marcador simples de fibrose hepática que complementa o FIB-4. Originalmente validado para hepatite C, hoje é amplamente utilizado como triagem geral de fibrose. A OMS recomenda o APRI em contextos com recursos limitados onde a elastografia não está disponível — diretamente relevante para grande parte do sistema de saúde brasileiro. Requer apenas dois valores laboratoriais (AST e contagem de plaquetas), tornando-o um dos índices mais acessíveis para avaliação hepática.',

  ascvd:
    'O escore ASCVD (Atherosclerotic Cardiovascular Disease) estima o risco de um primeiro evento cardiovascular aterosclerótico (infarto ou AVC) em 10 anos, utilizando as Equações de Coorte Agrupadas (Pooled Cohort Equations) do ACC/AHA. É a ferramenta de predição de risco CV mais reconhecida mundialmente. Requer dados clínicos adicionais (pressão arterial, tabagismo, tratamento para hipertensão, status de diabetes) além dos exames laboratoriais. Validado principalmente para idades entre 40 e 79 anos. As equações foram derivadas de coortes americanas e podem sobre ou subestimar o risco na população brasileira.',

  'castelli-i':
    'O Índice de Castelli I é a razão entre colesterol total e HDL-C, um dos índices lipídicos clássicos endossados pelos pesquisadores originais do Estudo de Framingham. Amplamente utilizado na prática clínica brasileira e frequentemente referenciado nas diretrizes de cardiologia da Sociedade Brasileira de Cardiologia (SBC). Os limiares de risco são diferenciados por sexo, refletindo diferenças fisiológicas no metabolismo lipídico. É um indicador simples e intuitivo que os usuários compreendem facilmente.',

  'castelli-ii':
    'O Índice de Castelli II é a razão entre LDL-C e HDL-C, complementando o Índice I com foco específico na fração aterogênica do colesterol. Junto com o Castelli I, forma a base da avaliação lipídica clássica do Estudo de Framingham. Os limiares também são diferenciados por sexo. Quando compartilhado com médicos brasileiros, estes índices são imediatamente reconhecidos, pois as diretrizes da SBC os referenciam diretamente.',

  egfr: 'A Taxa de Filtração Glomerular estimada (eGFR) pela equação CKD-EPI 2021 é o padrão-ouro não invasivo para estimar a função renal. A versão 2021 remove o coeficiente racial presente em equações anteriores, sendo a versão apropriada para implementação. A creatinina sérica está presente em virtualmente todo painel metabólico, tornando este possivelmente o escore de saúde mais universalmente calculável. O estadiamento segue os critérios KDIGO (G1 a G5). É importante notar que a eGFR isolada não diagnostica doença renal crônica — o diagnóstico requer eGFR < 60 ou evidência de dano renal sustentado por 3 meses ou mais.',

  fib4: 'O FIB-4 é um índice de triagem não invasiva recomendado pela AASLD (Associação Americana para o Estudo de Doenças Hepáticas) e EASL (Associação Europeia para o Estudo do Fígado) como avaliação de primeira linha em pacientes com suspeita de doença hepática gordurosa (NAFLD/MASLD). Combina idade, AST, ALT e contagem de plaquetas para estimar o risco de fibrose hepática avançada (estágios F3–F4). Valores baixos têm valor preditivo negativo de aproximadamente 90%, descartando fibrose significativa com boa confiabilidade. Não é projetado para diferenciar estágios leves de fibrose (F0–F2).',

  fli: 'O Índice de Gordura Hepática (FLI) prediz esteatose hepática (fígado gorduroso) combinando triglicerídeos, GGT, IMC e circunferência abdominal. Validado como ferramenta de triagem com AUROC de aproximadamente 0,84 para detecção de esteatose por ultrassonografia. É útil para identificar pessoas que podem se beneficiar de intervenções no estilo de vida antes que a fibrose se desenvolva. Requer dados antropométricos adicionais (circunferência abdominal) além dos exames laboratoriais.',

  'homa-ir':
    'O HOMA-IR (Homeostatic Model Assessment for Insulin Resistance) é o padrão de referência para estimar resistência à insulina a partir de exames de sangue em jejum. Universalmente reconhecido em pesquisa clínica e na prática médica. Complementa o Índice TyG — mostre HOMA-IR quando a insulina está no painel, TyG quando não está. Um estudo de Geloneze et al. (2006) em coorte brasileira estabeleceu HOMA-IR ≥ 2,71 como ponto de corte para resistência à insulina na população brasileira, alinhado ao limiar geral de ≥ 3,0 usado internacionalmente.',

  nlr: 'A Razão Neutrófilos-Linfócitos (NLR) é o marcador inflamatório mais simples e estudado derivado do hemograma, com mais de 10.000 citações no PubMed. NLR elevado reflete o equilíbrio entre respostas imunes inata (neutrófilos) e adaptativa (linfócitos), sendo um preditor validado de desfechos adversos em diversas condições — oncologia, cardiologia, doenças infecciosas e pesquisa metabólica. A tendência ao longo do tempo é mais significativa que uma única leitura, e doenças agudas ou infecções recentes podem elevar transitoriamente estes valores.',

  sii: 'O Índice Imuno-Inflamatório Sistêmico (SII) é um marcador composto de inflamação derivado do hemograma completo, combinando plaquetas, neutrófilos e linfócitos. Prediz eventos cardiovasculares, prognóstico oncológico, mortalidade por todas as causas e síndrome metabólica. Publicado extensivamente desde 2014 com base de evidências em rápido crescimento. Todos os valores de entrada vêm do hemograma completo com diferencial, o exame laboratorial mais comumente solicitado no Brasil.',

  tyg: 'O Índice TyG (Triglyceride-Glucose) é um marcador substituto de resistência à insulina que não requer dosagem de insulina — crucial porque muitos painéis laboratoriais básicos brasileiros (check-up básico) incluem glicemia de jejum e triglicerídeos, mas não insulina de jejum. O TyG foi validado contra o padrão-ouro (clamp euglicêmico) e HOMA-IR em múltiplos estudos, com valores de AUROC entre 0,75 e 0,85 para detecção de resistência à insulina. Inclui validação específica em coorte brasileira por da Silva et al. (2019).',
};
